config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: [:show]
    resources :categories,          only: [:show], param: :taxon_id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potepan/product_decorator.rb
Spree::Product.class_eval do
  scope :related_products, -> (product) do
    in_taxons(product.taxons).includes(master: [:default_price, :images]).where.not(id: product.id).distinct
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:taxon_id])
    @taxonomies = Spree::Taxonomy.includes(:root)
    @products = @taxon.products.includes(master: [:default_price, :images])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_DISPLAY_RELATED_NUMBER = 4

  def show
    @product = Spree::Product.find(params[:id])
    @product_properties = @product.product_properties.includes(:property)
    @related_products = Spree::Product.related_products(@product).limit(MAX_DISPLAY_RELATED_NUMBER)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li><span><a data-toggle="modal" href='#login'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>Create an account</a></span></li>
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">Search</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>Item(s) in your cart</li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default">Shopping Cart</button>
                    <button type="button" class="btn btn-default">Checkout</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html"><%= image_tag("img/logo.png", :alt => "") %></a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="index.html">Home</a></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <li><a href="product_grid_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                  <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                  <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                  <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                  <li class="listHeading">Others</li>
                  <li><a href="single-product.html">Single Product</a></li>
                  <li class="active"><a href="cart_page.html">Cart Page</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                  <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                  <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                  <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                  <li><a href="checkout_complete.html">Order Complete</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li><a href="about_us.html">About Us</a></li>
              <li><a href="signup.html">Register</a></li>
              <li><a href="signup-login.html">Register or Login</a></li>
              <li><a href="login.html">Login</a></li>
              <li><a href="lost-password.html">Password Recovery</a></li>
              <li><a href="privacy_policy.html">Privacy Policy</a></li>
              <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li>
              <li><a href="404.html">404 Not Found</a></li>
              <li><a href="coming-soon.html">Coming Soon</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="blog_right_sidebar.html">Right Sidebar</a></li>
              <li><a href="blog_left_sidebar.html">Left Sidebar</a></li>
              <li><a href="blog-fullwidth.html">Full Width</a></li>
              <li><a href="blog-single-fullwidth.html">Single Post</a></li>
              <li><a href="blog_single_right_sidebar.html">Single Right Sidebar</a></li>
              <li><a href="blog_single_left_sidebar.html">Single Left Sidebar</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="account-dashboard.html">Dashboard</a></li>
              <li><a href="account-profile.html">Profile</a></li>
              <li><a href="account-all-orders.html">All Orders</a></li>
              <li><a href="account-single-order.html">Single Order</a></li>
              <li><a href="account-wishlist.html">Wishlist</a></li>
              <li><a href="account-address.html">Address</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/layouts/_light_section_footer.html.erb
<!-- FOOTER LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_product_quick_view_modal.html.erb
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>149円</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sign_up_modal.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
  </head>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/sign_up_modal' %>
    <%= render 'layouts/product_quick_view_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_side_bar_color_selection.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <li><a href="#">ブラック<span>(15)</span></a></li>
      <li><a href="#">ホワイト<span>(10)</span></a></li>
      <li><a href="#">レッド<span>(7)</span></a></li>
      <li><a href="#">ブルー<span>(12)</span></a></li>
      <li><a href="#">オレンジ<span>(12)</span></a></li>
    </ul>
  </div>
</div>

app/views/potepan/categories/_side_bar_filter_area.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>

app/views/potepan/categories/_side_bar_product_categories.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomies.each do |taxonomy| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#taxon_<%= taxonomy.id %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
            <ul id="taxon_<%= taxonomy.id %>" class="collapse collapseItem">
              <% taxonomy.root.leaves.each do |taxon| %>
                <li>
                  <%= link_to potepan_category_path(taxon.id) do %>
                    <i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %><span>(<%= taxon.products.count %>)</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_side_bar_size_selection.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <li><a href="#">S<span>(15)</span></a></li>
      <li><a href="#">M<span>(10)</span></a></li>
      <li><a href="#">L<span>(7)</span></a></li>
      <li><a href="#">XL<span>(12)</span></a></li>
    </ul>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<%= provide(:title, "Categories") %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li>
            <%= link_to "Shop", potepan_path %>
          </li>
          <li class="active"><%= @taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <%= render 'potepan/categories/side_bar_product_categories', taxonomies: @taxonomies %>
        <%= render 'potepan/categories/side_bar_color_selection' %>
        <%= render 'potepan/categories/side_bar_size_selection' %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <%= render 'potepan/categories/side_bar_filter_area' %>
        <div class="row">
          <% @products.each do |product| %>
            <div class="col-sm-4 col-xs-12">
              <div class="productBox">
                <%= link_to potepan_product_path(product.id) do %>
                  <div class="productImage clearfix">
                    <%= image_tag product.display_image.attachment(:product) %>
                  </div>
                  <div class="productCaption clearfix">
                    <h5><%= product.name %></h5>
                    <h3><%= product.display_price %></h3>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/light_section_footer' %>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.each do |related_product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="productBox">
        <div>
          <%= link_to potepan_product_path(related_product.id) do %>
            <div class="productImage clearfix">
              <%= image_tag(related_product.display_image.attachment.url(:large), :alt => "#{related_product.name}-img") %>
            </div>
            <div class="productCaption clearfix">
              <h5><%= related_product.name %></h5>
              <h3><%= related_product.display_price %></h3>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/products/show.html.erb
<%= provide(:title, "Product Details") %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li class="active"><%= @product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @product.images.each.with_index do |img, i| %>
                  <div class="item<%=" active" if i.zero? %>" data-thumb="<%= i %>">
                    <%= image_tag img.attachment.url(:large) %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% @product.images.each.with_index do |img, i|%>
                    <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                      <%= image_tag img.attachment.url(:small) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                <li><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a></li>
              <% end %>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <% if @product.product_option_types.exists? %>
              <span class="quick-drop">
                <select name="guiest_id3" id="guiest_id3" class="select-drop">
                  <%= options_from_collection_for_select @product.option_types.first.try(:option_values), 'id', 'presentation' %>
                </select>
              </span>
            <% end %>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
            <div class="columns six alpha" data-hook="product_left_part">
              <div class="row" data-hook="product_left_part_wrap">
                <div data-hook="product_properties">
                  <% if @product_properties.present? %>
                    <h5 class="product-section-title"><%= t('spree.properties')%></h5>
                    <table id="product-properties" class="table-display" data-hook>
                      <tbody>
                        <% @product_properties.each do |product_property| %>
                          <% css_class = cycle('even', 'odd', name: "properties") %>
                          <tr class="<%= css_class %>">
                            <td><strong><%= product_property.property.presentation %></strong></td>
                            <td><%= product_property.value %></td>
                          </tr>
                        <% end %>
                        <% reset_cycle('properties') %>
                      </tbody>
                    </table>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render 'potepan/products/related_products', related_products: @related_products %>
  </div>
</section>

app/views/potepan/sample/checkout_complete.html.erb
<%= provide(:title,"Order Completed") %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2>thanks message</h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <li class="active">thanks message</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix setp5">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="thanksContent">
          <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
          <h3>Shipping Details</h3>
          <div class="thanksInner">
            <div class="row">
              <div class="col-sm-6 col-xs-12 tableBlcok">
                <address>
                  <span>Shipping address:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                  <span>Email:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                  <span>Phone:</span> +884 5452 6432
                </address>
              </div>
              <div class="col-sm-6 col-xs-12">
                <div class="well">
                  <h2><small>Order ID</small>9547</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>